version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    ports:
      - "33061:$DB_PORT"
    env_file:
      - .env
    environment:
      - "MYSQL_ROOT_PASSWORD=$DB_PASSWORD"
      - "MYSQL_USER=$DB_USERNAME"
      - "MYSQL_PASSWORD=$DB_PASSWORD"
      - "MYSQL_DATABASE=$DB_DATABASE"

  redis:
    image: redis:3.0
    ports:
      - "63791:$REDIS_PORT"
